// Shape library seed.
// shape_seeds() is auto-generated by build.rs from frontend/public/shapes/.
// Do not hand-edit shape data here — edit the JSON/SVG files instead.

use tracing::{info, warn};

struct ShapeSeed {
    shape_id: &'static str,
    category: &'static str,
    shape_type: &'static str,
    svg_data: &'static str,
    sidecar: &'static str,
}

include!(concat!(env!("OUT_DIR"), "/shape_seeds.rs"));

pub async fn seed_shape_library(db: &io_db::DbPool) {
    let shapes = shape_seeds();
    let current_ids: Vec<String> = shapes.iter().map(|s| s.shape_id.to_string()).collect();

    let mut upserted = 0u32;

    for s in &shapes {
        let sidecar_value: serde_json::Value =
            serde_json::from_str(s.sidecar).unwrap_or_else(|e| {
                warn!(shape_id = %s.shape_id, error = %e, "Failed to parse sidecar JSON");
                serde_json::json!({})
            });

        let display_name = sidecar_value["display_name"]
            .as_str()
            .unwrap_or(s.shape_id)
            .to_string();

        let view_box = sidecar_value["geometry"]["viewBox"]
            .as_str()
            .unwrap_or("")
            .to_string();

        let metadata = serde_json::json!({
            "shape_id": s.shape_id,
            "source": "library",
            "display_name": &display_name,
            "category": s.category,
            "view_box": &view_box,
            "schema": "io-shape-v1",
            "sidecar": sidecar_value
        });

        let result: Result<sqlx::postgres::PgQueryResult, _> = sqlx::query(
            r#"
            INSERT INTO design_objects (id, name, type, svg_data, metadata, created_at, updated_at)
            VALUES (gen_random_uuid(), $1, $2, $3, $4::jsonb, NOW(), NOW())
            ON CONFLICT ((metadata->>'shape_id'))
                WHERE type IN ('shape', 'shape_part') AND metadata->>'source' = 'library'
            DO UPDATE SET
                name       = EXCLUDED.name,
                svg_data   = EXCLUDED.svg_data,
                metadata   = EXCLUDED.metadata,
                updated_at = NOW()
            "#,
        )
        .bind(&display_name)
        .bind(s.shape_type)
        .bind(s.svg_data)
        .bind(metadata.to_string())
        .execute(db)
        .await;

        match result {
            Ok(_) => upserted += 1,
            Err(e) => warn!(shape_id = %s.shape_id, error = %e, "Failed to upsert shape"),
        }
    }

    // Delete orphaned library shapes whose IDs are no longer in the current set.
    // These are legacy entries from old seed data (e.g., "compressor" replaced by
    // "compressor-opt1"/"compressor-opt2").
    let deleted = sqlx::query(
        r#"
        DELETE FROM design_objects
        WHERE type IN ('shape', 'shape_part')
          AND metadata->>'source' = 'library'
          AND NOT (metadata->>'shape_id' = ANY($1))
        "#,
    )
    .bind(&current_ids)
    .execute(db)
    .await
    .map(|r| r.rows_affected())
    .unwrap_or_else(|e| {
        warn!(error = %e, "Failed to delete orphaned library shapes");
        0
    });

    info!(
        upserted,
        deleted,
        total = shapes.len(),
        "Shape library seed complete"
    );
}
