// Shape library seed.
// shape_seeds() is auto-generated by build.rs from frontend/shapes-source/.
// Do not hand-edit shape data here — edit the JSON/SVG files instead.

use crate::shape_hash;
use tracing::{info, warn};

struct ShapeSeed {
    shape_id: &'static str,
    category: &'static str,
    shape_type: &'static str,
    svg_data: &'static str,
    sidecar: &'static str,
}

include!(concat!(env!("OUT_DIR"), "/shape_seeds.rs"));

pub async fn seed_shape_library(db: &io_db::DbPool) {
    let shapes = shape_seeds();
    let current_ids: Vec<String> = shapes.iter().map(|s| s.shape_id.to_string()).collect();

    let mut inserted = 0u32;
    let mut skipped = 0u32;

    for s in &shapes {
        let sidecar_value: serde_json::Value =
            serde_json::from_str(s.sidecar).unwrap_or_else(|e| {
                warn!(shape_id = %s.shape_id, error = %e, "Failed to parse sidecar JSON");
                serde_json::json!({})
            });

        let display_name = sidecar_value["display_name"]
            .as_str()
            .unwrap_or(s.shape_id)
            .to_string();

        let view_box = sidecar_value["geometry"]["viewBox"]
            .as_str()
            .unwrap_or("")
            .to_string();

        if let Err(errors) = shape_hash::validate_sidecar(&sidecar_value) {
            warn!(
                shape_id = %s.shape_id,
                error_count = errors.len(),
                first_error = %errors.first().map(|e| e.as_str()).unwrap_or(""),
                "Sidecar schema validation warning (not blocking)"
            );
        }

        let computed_sidecar_hash = shape_hash::sidecar_hash(&sidecar_value);
        let computed_svg_hash = shape_hash::svg_hash(s.svg_data);

        let metadata = serde_json::json!({
            "shape_id": s.shape_id,
            "source": "library",
            "display_name": &display_name,
            "category": s.category,
            "view_box": &view_box,
            "schema": "io-shape-v1",
            "sidecar": sidecar_value,
            "sidecar_hash": computed_sidecar_hash,
            "svg_hash": computed_svg_hash
        });

        let result: Result<sqlx::postgres::PgQueryResult, _> = sqlx::query(
            r#"
            INSERT INTO design_objects (id, name, type, svg_data, metadata, created_at, updated_at)
            VALUES (gen_random_uuid(), $1, $2, $3, $4::jsonb, NOW(), NOW())
            ON CONFLICT ((metadata->>'shape_id'))
                WHERE type IN ('shape', 'shape_part') AND metadata->>'source' = 'library'
            DO NOTHING
            "#,
        )
        .bind(&display_name)
        .bind(s.shape_type)
        .bind(s.svg_data)
        .bind(metadata.to_string())
        .execute(db)
        .await;

        match result {
            Ok(r) => {
                if r.rows_affected() > 0 {
                    inserted += 1;
                } else {
                    skipped += 1;
                }
            }
            Err(e) => warn!(shape_id = %s.shape_id, error = %e, "Failed to insert shape"),
        }
    }

    // Orphan cleanup: delete library shapes whose IDs are no longer in the current
    // binary. Gated behind IO_SEED_ORPHAN_CLEANUP=1 to prevent accidental deletion
    // of shapes added via SQL migration (those IDs may not be in the binary yet if
    // the migration was deployed before the next binary release).
    let deleted = if std::env::var("IO_SEED_ORPHAN_CLEANUP").as_deref() == Ok("1") {
        sqlx::query(
            r#"
            DELETE FROM design_objects
            WHERE type IN ('shape', 'shape_part')
              AND metadata->>'source' = 'library'
              AND NOT (metadata->>'shape_id' = ANY($1))
            "#,
        )
        .bind(&current_ids)
        .execute(db)
        .await
        .map(|r| r.rows_affected())
        .unwrap_or_else(|e| {
            warn!(error = %e, "Failed to delete orphaned library shapes");
            0
        })
    } else {
        0
    };

    info!(
        inserted,
        skipped,
        deleted,
        total = shapes.len(),
        "Shape library seed complete"
    );
}
