-- no-transaction
DROP MATERIALIZED VIEW IF EXISTS points_history_1d CASCADE;
DROP MATERIALIZED VIEW IF EXISTS points_history_1h CASCADE;
DROP MATERIALIZED VIEW IF EXISTS points_history_15m CASCADE;
DROP MATERIALIZED VIEW IF EXISTS points_history_5m CASCADE;
DROP MATERIALIZED VIEW IF EXISTS points_history_1m CASCADE;
