use std::fmt::Write as FmtWrite;
use std::fs;
use std::path::Path;

fn main() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let shapes_root = Path::new(&manifest_dir).join("../../frontend/shapes-source");

    // Tell Cargo to rerun this script if any shape file changes
    println!("cargo:rerun-if-changed={}", shapes_root.display());
    println!(
        "cargo:rerun-if-changed={}",
        shapes_root
            .join("_schema/io-shape-v1.schema.json")
            .display()
    );

    let out_dir = std::env::var("OUT_DIR").unwrap();
    let out_path = Path::new(&out_dir).join("shape_seeds.rs");

    // Collect (shape_id, category, svg_content, sidecar_json) for all shapes
    let mut entries: Vec<(String, String, String, String)> = Vec::new();

    let cat_entries = fs::read_dir(&shapes_root)
        .unwrap_or_else(|e| panic!("Cannot read shapes dir {}: {}", shapes_root.display(), e));

    for cat_entry in cat_entries {
        let cat_entry = cat_entry.unwrap();
        let cat_path = cat_entry.path();
        if !cat_path.is_dir() {
            continue;
        }
        let category = cat_path.file_name().unwrap().to_str().unwrap().to_string();
        // Skip hidden/schema directories
        if category.starts_with('_') || category.starts_with('.') {
            continue;
        }

        for shape_entry in fs::read_dir(&cat_path).unwrap() {
            let shape_entry = shape_entry.unwrap();
            let shape_path = shape_entry.path();
            let ext = shape_path
                .extension()
                .and_then(|e| e.to_str())
                .unwrap_or("");
            if ext != "json" {
                continue;
            }

            let stem = shape_path
                .file_stem()
                .unwrap()
                .to_str()
                .unwrap()
                .to_string();

            let sidecar = fs::read_to_string(&shape_path)
                .unwrap_or_else(|e| panic!("Cannot read {}: {}", shape_path.display(), e));

            // Determine SVG filename from sidecar (variants.options first entry, or {stem}.svg)
            let svg_filename = determine_svg_filename(&sidecar, &stem);
            let svg_path = cat_path.join(&svg_filename);

            if !svg_path.exists() {
                panic!(
                    "SVG missing for shape {}: expected {}",
                    stem,
                    svg_path.display()
                );
            }

            let svg = fs::read_to_string(&svg_path)
                .unwrap_or_else(|e| panic!("Cannot read {}: {}", svg_path.display(), e));

            entries.push((stem, category.clone(), svg, sidecar));
        }
    }

    entries.sort_by(|a, b| a.0.cmp(&b.0));
    let count = entries.len();

    // Generate shape_seeds.rs
    let mut output = String::new();
    writeln!(
        output,
        "// AUTO-GENERATED by build.rs — DO NOT EDIT MANUALLY"
    )
    .unwrap();
    writeln!(output, "fn shape_seeds() -> Vec<ShapeSeed> {{").unwrap();
    writeln!(output, "    vec![").unwrap();

    for (shape_id, category, svg, sidecar) in &entries {
        let shape_type = if shape_id.starts_with("part-") {
            "shape_part"
        } else {
            "shape"
        };
        writeln!(output, "        ShapeSeed {{").unwrap();
        // Use Debug formatting ("{:?}") which produces a valid escaped Rust string literal
        writeln!(
            output,
            "            shape_id: {},",
            format_args!("{:?}", shape_id)
        )
        .unwrap();
        writeln!(
            output,
            "            category: {},",
            format_args!("{:?}", category)
        )
        .unwrap();
        writeln!(
            output,
            "            shape_type: {},",
            format_args!("{:?}", shape_type)
        )
        .unwrap();
        writeln!(
            output,
            "            svg_data: {},",
            format_args!("{:?}", svg)
        )
        .unwrap();
        writeln!(
            output,
            "            sidecar: {},",
            format_args!("{:?}", sidecar)
        )
        .unwrap();
        writeln!(output, "        }},").unwrap();
    }

    writeln!(output, "    ]").unwrap();
    writeln!(output, "}}").unwrap();

    fs::write(&out_path, output)
        .unwrap_or_else(|e| panic!("Cannot write {}: {}", out_path.display(), e));

    // Emit count as a build warning so it shows in build output
    println!("cargo:warning=Shape seeds generated: {}", count);
}

fn determine_svg_filename(sidecar_json: &str, stem: &str) -> String {
    if let Ok(v) = serde_json::from_str::<serde_json::Value>(sidecar_json) {
        // Try variants.options — take the first option's file
        if let Some(opts) = v["variants"]["options"].as_object() {
            for (_, opt_val) in opts.iter() {
                if let Some(file) = opt_val["file"].as_str() {
                    return file.to_string();
                }
            }
        }
    }
    format!("{}.svg", stem)
}
