import { api, queryString } from './client'
import type { GraphicDocument, GraphicSummary } from '../shared/types/graphics'

export interface DesignObjectSummary extends GraphicSummary {}

export interface DesignObjectCreateRequest {
  name: string
  scene_data: GraphicDocument
}

export interface DesignObjectUpdateRequest {
  name?: string
  scene_data?: GraphicDocument
}

export interface ShapeBatchResponse {
  [shapeId: string]: {
    svg: string
    sidecar: Record<string, unknown>
  }
}

export interface GraphicHierarchyNode {
  id: string
  name: string
  graphicId?: string
  children: GraphicHierarchyNode[]
}

export const graphicsApi = {
  /** Get the view hierarchy tree for navigation (scope=process) */
  getHierarchy: () =>
    api.get<{ tree: GraphicHierarchyNode[] }>('/api/graphics/hierarchy?scope=process'),

  /** List all design objects (graphics) */
  list: (params?: { scope?: 'console' | 'process'; mode?: 'graphic' | 'dashboard' | 'report' }) =>
    api.get<{ data: DesignObjectSummary[]; total: number }>(
      `/api/v1/design-objects${queryString(params as Record<string, unknown>)}`
    ),

  /** Get a single graphic by ID */
  get: (id: string) =>
    api.get<{ data: { id: string; name: string; scene_data: GraphicDocument; version: number; updatedAt: string; locked_by: string | null; locked_by_name: string | null; locked_at: string | null } }>(
      `/api/v1/design-objects/${id}`
    ),

  /**
   * Acquire pessimistic edit lock on a design object.
   * Returns { acquired: true } if the lock was granted, or
   * { acquired: false; locked_by_name: string; locked_at: string } if already locked.
   */
  acquireLock: (id: string) =>
    api.post<{ data: { acquired: boolean; locked_by_name?: string; locked_at?: string } }>(
      `/api/v1/design-objects/${id}/lock`, {}
    ),

  /** Release the edit lock on a design object. */
  releaseLock: (id: string) =>
    api.delete(`/api/v1/design-objects/${id}/lock`),

  /** Create a new graphic */
  create: (payload: DesignObjectCreateRequest) =>
    api.post<{ data: { id: string } }>('/api/v1/design-objects', payload),

  /** Update an existing graphic */
  update: (id: string, payload: DesignObjectUpdateRequest) =>
    api.put<{ data: { id: string; version: number } }>(`/api/v1/design-objects/${id}`, payload),

  /** Delete a graphic */
  remove: (id: string) =>
    api.delete(`/api/v1/design-objects/${id}`),

  /** Batch fetch shapes from the shape library */
  batchShapes: (shapeIds: string[]) =>
    api.post<ShapeBatchResponse>('/api/v1/shapes/batch', { shapeIds }),

  /** Get a graphic's thumbnail URL */
  thumbnailUrl: (id: string) => `/api/v1/design-objects/${id}/thumbnail.png`,

  /**
   * Leaflet-compatible tile URL template for a pre-rendered tile pyramid (doc 20 §Tile Viewer).
   * Pass this to L.tileLayer(). Tiles are 256×256 PNGs generated by resvg server-side.
   */
  tileUrl: (id: string) => `/api/v1/design-objects/${id}/tiles/{z}/{x}/{y}.png`,

  /** List stencils from the design_objects table */
  listStencils: () =>
    api.get<{ data: Array<{ id: string; name: string; type: string; svg_data?: string; metadata?: Record<string, unknown> }> }>(
      '/api/v1/design-objects?type=stencil'
    ),

  /** Save selected elements as a stencil */
  createStencil: (payload: { name: string; category: string; tags?: string; svgData?: string; nodes?: unknown }) =>
    api.post<{ data: { id: string } }>('/api/v1/design-objects', {
      name: payload.name,
      type: 'stencil',
      svg_data: payload.svgData ?? '',
      metadata: { category: payload.category, tags: payload.tags ?? '', nodes: payload.nodes ?? null },
    }),

  /** Upload an image asset */
  uploadImage: (file: File) => {
    const form = new FormData()
    form.append('file', file)
    return api.post<{ data: { hash: string; url: string } }>('/api/v1/image-assets', form)
  },

  /** Get image asset URL by hash */
  imageUrl: (hash: string) => `/api/v1/image-assets/${hash}`,

  /**
   * Export a shape's raw SVG content as a standalone file.
   * Returns the SVG as a text string.
   * Available for all shapes (library + user-created).
   */
  exportShapeSvg: async (shapeId: string): Promise<string> => {
    const resp = await fetch(`/api/v1/shapes/${shapeId}/svg`, {
      method: 'GET',
      credentials: 'include',
    })
    if (!resp.ok) throw new Error(`Export failed: ${resp.statusText}`)
    return resp.text()
  },

  /**
   * Replace a user-created shape's SVG content.
   * Library shapes (source=library) are read-only.
   * Sidecar metadata is preserved — only the visual geometry changes.
   */
  reimportShapeSvg: (shapeId: string, svgContent: string) =>
    api.put<{ data: { viewBoxChanged: boolean; oldViewBox: string; newViewBox: string } }>(
      `/api/v1/shapes/${shapeId}/svg`,
      { svg_content: svgContent }
    ),

  // ── Versioning ──────────────────────────────────────────────────────────

  /** List all versions (drafts + published) for a graphic. */
  getVersions: (id: string) =>
    api.get<{ data: Array<{
      id: string
      version: number
      type: 'published' | 'draft'
      author: string
      author_name: string
      timestamp: string
      isCurrent?: boolean
    }> }>(`/api/v1/design-objects/${id}/versions`),

  /** Get the scene_data for a specific version. */
  getVersionContent: (id: string, versionId: string) =>
    api.get<{ data: { scene_data: import('../shared/types/graphics').GraphicDocument } }>(
      `/api/v1/design-objects/${id}/versions/${versionId}`
    ),

  /**
   * Publish the current draft as a permanent immutable snapshot.
   * Returns the new version number.
   */
  publishGraphic: (id: string) =>
    api.post<{ data: { version: number } }>(`/api/v1/design-objects/${id}/publish`, {}),

  /**
   * Restore a previous version — creates a new draft from the old version's content.
   * Returns the new draft version number.
   */
  restoreVersion: (id: string, versionId: string) =>
    api.post<{ data: { version: number } }>(
      `/api/v1/design-objects/${id}/versions/${versionId}/restore`, {}
    ),

  /** Export a graphic as a .iographic ZIP (returns Blob) */
  exportIographic: async (id: string, description?: string): Promise<Blob> => {
    const resp = await fetch(`/api/v1/design-objects/${id}/export/iographic`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ description: description ?? '' }),
      credentials: 'include',
    })
    if (!resp.ok) throw new Error(`Export failed: ${resp.statusText}`)
    return resp.blob()
  },

  /** Analyze a .iographic file before import (returns structured analysis) */
  analyzeIographic: async (file: File): Promise<IographicAnalysis> => {
    const form = new FormData()
    form.append('file', file)
    const resp = await fetch('/api/v1/design-objects/import/iographic/analyze', {
      method: 'POST',
      body: form,
      credentials: 'include',
    })
    if (!resp.ok) {
      const err = await resp.json().catch(() => ({ message: resp.statusText }))
      throw new Error(err.message ?? 'Analysis failed')
    }
    const json = await resp.json()
    return json.data as IographicAnalysis
  },

  /** Commit an import after user resolves decisions */
  commitIographic: async (file: File, options: IographicImportOptions): Promise<IographicImportResult> => {
    const form = new FormData()
    form.append('file', file)
    form.append('options', JSON.stringify(options))
    const resp = await fetch('/api/v1/design-objects/import/iographic', {
      method: 'POST',
      body: form,
      credentials: 'include',
    })
    if (!resp.ok) {
      const err = await resp.json().catch(() => ({ message: resp.statusText }))
      throw new Error(err.message ?? 'Import failed')
    }
    const json = await resp.json()
    return json.data as IographicImportResult
  },
}

// ── .iographic import/export types ──────────────────────────────────────────

export interface IographicManifest {
  format: 'iographic'
  format_version: string
  generator: { application: string; version: string; instance_id?: string }
  exported_at: string
  exported_by: string
  description?: string
  graphics: Array<{ directory: string; name: string; type: string }>
  shapes: Array<{ directory: string; name: string; shape_id: string }>
  stencils: Array<{ directory: string; name: string }>
  shape_dependencies: string[]
  point_tags: string[]
  checksum: string
}

export interface IographicTagResolution {
  tag: string
  source_hint?: string
  status: 'resolved' | 'ambiguous' | 'unresolved'
  resolved_to?: string  // point UUID if resolved
  candidates?: Array<{ id: string; tagname: string; source: string }>
}

export interface IographicShapeStatus {
  shape_id: string
  name?: string
  status: 'available' | 'missing' | 'custom_new' | 'custom_exists'
  action?: 'import' | 'use_existing' | 'import_as_copy' | 'skip'
}

export interface IographicAnalysis {
  manifest: IographicManifest
  tag_resolutions: IographicTagResolution[]
  shape_statuses: IographicShapeStatus[]
  stencil_statuses: Array<{ stencil_id: string; name: string; status: 'new' | 'exists' }>
  valid: boolean
  errors: string[]
}

export interface IographicImportOptions {
  tag_mappings: Array<{ original_tag: string; mapped_tag?: string; action: 'keep' | 'remap' | 'skip' }>
  shape_actions: Array<{ shape_id: string; action: 'import' | 'use_existing' | 'import_as_copy' | 'skip' }>
  stencil_actions: Array<{ stencil_id: string; action: 'import' | 'use_existing' | 'skip' }>
  target_name?: string
  import_as: 'draft' | 'published'
  overwrite: boolean
}

export interface IographicImportResult {
  graphics_imported: number
  shapes_imported: number
  stencils_imported: number
  bindings_resolved: number
  bindings_unresolved: number
  bindings_total: number
  unresolved_tags: string[]
  missing_shapes: string[]
  graphic_ids: string[]
}
