#!/usr/bin/env python3
"""rebuild-index.py — Deterministically rebuilds .claude/docs/index.json and
.claude/docs/INDEX.md from interim doc frontmatter.

Reads every .claude/docs/interim/*.md, parses frontmatter via lib-frontmatter.py,
and writes two output files atomically (temp-then-rename).

Alias collision detection: exits 1 without writing if any alias maps to more
than one doc, or if an alias duplicates an existing slug.

Usage:
    python3 rebuild-index.py
"""

import json
import os
import subprocess
import sys
import tempfile
from datetime import datetime, timezone
from glob import glob
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent
DOCS_DIR = Path(__file__).parents[2] / "docs"
INTERIM_DIR = DOCS_DIR / "interim"
INDEX_JSON = DOCS_DIR / "index.json"
INDEX_MD = DOCS_DIR / "INDEX.md"


def parse_frontmatter(path: Path) -> dict | None:
    result = subprocess.run(
        [sys.executable, str(SCRIPT_DIR / "lib-frontmatter.py"), "parse", str(path)],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        print(f"ERROR: failed to parse {path}: {result.stderr.strip()}", file=sys.stderr)
        return None
    try:
        return json.loads(result.stdout)
    except json.JSONDecodeError as e:
        print(f"ERROR: invalid JSON from lib-frontmatter for {path}: {e}", file=sys.stderr)
        return None


def build_doc_entry(slug: str, fm: dict) -> dict:
    impl = fm.get("implementation") or []
    wu = fm.get("work_units") or []
    return {
        "slug": slug,
        "id": fm.get("id") or slug,
        "title": fm.get("title") or "",
        "covers": fm.get("covers") or "",
        "topics": sorted(fm.get("topics") or []),
        "aliases": sorted(fm.get("aliases") or []),
        "status": fm.get("status") or "",
        "created": fm.get("created") or None,
        "last_updated": fm.get("last_updated") or None,
        "needs_triage": bool(fm.get("needs_triage", False)),
        "merge_candidates": fm.get("merge_candidates") or [],
        "implementation_count": len(impl) if isinstance(impl, list) else 0,
        "work_unit_count": len(wu) if isinstance(wu, list) else 0,
        "path": f".claude/docs/interim/{slug}.md",
    }


def check_alias_collisions(docs: list[dict]) -> bool:
    """Returns True if collisions found (caller should exit 1)."""
    slug_set = {d["slug"] for d in docs}
    alias_owners: dict[str, str] = {}
    collisions_found = False
    for doc in docs:
        for alias in doc["aliases"]:
            if alias in slug_set:
                print(
                    f"ERROR: alias collision: '{alias}' claimed by '{doc['slug']}'"
                    f" but '{alias}' is also an existing slug",
                    file=sys.stderr,
                )
                collisions_found = True
            elif alias in alias_owners:
                print(
                    f"ERROR: alias collision: '{alias}' claimed by both"
                    f" '{alias_owners[alias]}' and '{doc['slug']}'",
                    file=sys.stderr,
                )
                collisions_found = True
            else:
                alias_owners[alias] = doc["slug"]
    return collisions_found


def build_topic_index(docs: list[dict]) -> dict[str, list[str]]:
    index: dict[str, list[str]] = {}
    for doc in docs:
        for topic in doc["topics"]:
            index.setdefault(topic, []).append(doc["slug"])
    return {k: sorted(v) for k, v in sorted(index.items())}


def build_alias_index(docs: list[dict]) -> dict[str, str]:
    index: dict[str, str] = {}
    for doc in docs:
        for alias in doc["aliases"]:
            index[alias] = doc["slug"]
    return dict(sorted(index.items()))


def write_atomic(path: Path, content: str) -> None:
    dir_ = path.parent
    with tempfile.NamedTemporaryFile(mode="w", dir=dir_, delete=False, suffix=".tmp") as f:
        f.write(content)
        tmp_path = f.name
    os.replace(tmp_path, path)


def render_index_md(docs: list[dict], topic_index: dict, triage_queue: list[str], generated: str) -> str:
    lines = [
        "<!-- GENERATED by rebuild-index.py. Do not hand-edit. Edit frontmatter in",
        "     individual docs, then re-run the rebuild. -->",
        "",
        "# Interim Documentation Index",
        "",
        f"Generated: {generated}",
        f"Total documents: {len(docs)}",
        "",
        "## Triage Queue",
        "",
        "<!-- Docs flagged by the matcher as ambiguous; review and merge or commit. -->",
        "",
    ]

    if not triage_queue:
        lines.append("_None._")
    else:
        triage_by_slug = {d["slug"]: d for d in docs}
        for slug in triage_queue:
            doc = triage_by_slug.get(slug, {})
            title = doc.get("title", "")
            candidates = doc.get("merge_candidates", [])
            cand_str = f" (merge candidates: {', '.join(candidates)})" if candidates else ""
            lines.append(f"- **{slug}** — {title}{cand_str}")

    lines += [
        "",
        "## By Topic",
        "",
    ]

    for topic, slugs in topic_index.items():
        lines.append(f"### {topic}")
        lines.append("")
        slug_map = {d["slug"]: d for d in docs}
        for slug in slugs:
            title = slug_map.get(slug, {}).get("title", "")
            lines.append(f"- **{slug}** — {title}")
        lines.append("")

    lines += [
        "## All Documents",
        "",
    ]

    for doc in docs:
        slug = doc["slug"]
        lines.append(f"### {slug}")
        lines.append("")
        lines.append(f"- **Title:** {doc['title']}")
        lines.append(f"- **Covers:** {doc['covers']}")
        topics_str = ", ".join(doc["topics"]) if doc["topics"] else "none"
        lines.append(f"- **Topics:** {topics_str}")
        lines.append(f"- **Status:** {doc['status']}")
        lines.append(f"- **Last updated:** {doc['last_updated'] or 'unknown'}")
        lines.append(f"- **Implementation:** {doc['implementation_count']} files")
        lines.append(f"- **Work units:** {doc['work_unit_count']}")
        aliases_str = ", ".join(doc["aliases"]) if doc["aliases"] else "none"
        lines.append(f"- **Aliases:** {aliases_str}")
        lines.append("")

    return "\n".join(lines)


def main() -> int:
    md_files = sorted(glob(str(INTERIM_DIR / "*.md")))
    if not md_files:
        print("rebuild-index: no interim docs found", file=sys.stderr)

    docs: list[dict] = []
    for path_str in md_files:
        path = Path(path_str)
        slug = path.stem
        fm = parse_frontmatter(path)
        if fm is None:
            continue
        docs.append(build_doc_entry(slug, fm))

    docs.sort(key=lambda d: d["slug"])

    if check_alias_collisions(docs):
        return 1

    topic_index = build_topic_index(docs)
    alias_index = build_alias_index(docs)
    triage_queue = sorted(d["slug"] for d in docs if d["needs_triage"])

    generated = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    index_data = {
        "generated": generated,
        "doc_count": len(docs),
        "docs": docs,
        "topic_index": topic_index,
        "alias_index": alias_index,
        "triage_queue": triage_queue,
    }

    index_json_str = json.dumps(index_data, indent=2, ensure_ascii=False)
    index_md_str = render_index_md(docs, topic_index, triage_queue, generated)

    write_atomic(INDEX_JSON, index_json_str + "\n")
    write_atomic(INDEX_MD, index_md_str + "\n")

    print(f"rebuild-index: wrote {len(docs)} docs to index.json and INDEX.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
