//! System info endpoints — `/api/system/...`
//!
//! These handlers return application metadata and open-source license information.
//! They are stubs that return placeholder data until the build pipeline produces
//! `backend-licenses.json` (via cargo-about) and `frontend-licenses.json`
//! (via license-checker).
//!
//! Any authenticated user may call these endpoints (doc 06 §About Page).

use axum::{
    body::Body,
    extract::State,
    http::{header, StatusCode},
    response::{IntoResponse, Response},
    Json,
};
use serde::Serialize;

use crate::state::AppState;

// ---------------------------------------------------------------------------
// Response types
// ---------------------------------------------------------------------------

#[derive(Serialize)]
pub struct AboutInfo {
    pub version: String,
    pub build: String,
    #[serde(rename = "serverHostname")]
    pub server_hostname: String,
    #[serde(rename = "eulaVersion")]
    pub eula_version: String,
}

#[derive(Serialize)]
pub struct LicenseEntry {
    pub name: String,
    pub version: String,
    pub license: String,
    pub copyright: String,
    pub text: String,
}

// ---------------------------------------------------------------------------
// Handlers
// ---------------------------------------------------------------------------

/// GET /api/system/about — returns application version, build info, and hostname.
pub async fn get_about(State(_state): State<AppState>) -> impl IntoResponse {
    let hostname = std::env::var("HOSTNAME")
        .or_else(|_| std::env::var("HOST"))
        .unwrap_or_else(|_| "unknown".into());

    let info = AboutInfo {
        version: env!("CARGO_PKG_VERSION").into(),
        build: option_env!("IO_BUILD_COMMIT")
            .unwrap_or("dev")
            .into(),
        server_hostname: hostname,
        eula_version: option_env!("IO_EULA_VERSION")
            .unwrap_or("1.0")
            .into(),
    };

    Json(serde_json::json!({ "success": true, "data": info }))
}

/// GET /api/system/licenses/backend — returns Rust/backend dependency license list.
///
/// In production this will read `backend-licenses.json` generated by cargo-about.
/// Currently returns a representative stub list.
pub async fn get_licenses_backend(State(_state): State<AppState>) -> impl IntoResponse {
    let entries: Vec<LicenseEntry> = vec![
        LicenseEntry {
            name: "axum".into(),
            version: "0.7".into(),
            license: "MIT".into(),
            copyright: "Copyright (c) 2019 Axum Contributors".into(),
            text: "MIT License\n\nPermission is hereby granted, free of charge, to any person obtaining a copy of this software...".into(),
        },
        LicenseEntry {
            name: "tokio".into(),
            version: "1".into(),
            license: "MIT".into(),
            copyright: "Copyright (c) 2019 Tokio Contributors".into(),
            text: "MIT License\n\nPermission is hereby granted, free of charge, to any person obtaining a copy of this software...".into(),
        },
        LicenseEntry {
            name: "sqlx".into(),
            version: "0.7".into(),
            license: "MIT OR Apache-2.0".into(),
            copyright: "Copyright (c) 2019 LaunchBadge".into(),
            text: "MIT License\n\nPermission is hereby granted, free of charge, to any person obtaining a copy of this software...".into(),
        },
        LicenseEntry {
            name: "serde".into(),
            version: "1".into(),
            license: "MIT OR Apache-2.0".into(),
            copyright: "Copyright (c) 2014+ Erick Tryzelaar and David Tolnay".into(),
            text: "MIT License\n\nPermission is hereby granted, free of charge, to any person obtaining a copy of this software...".into(),
        },
        LicenseEntry {
            name: "jsonwebtoken".into(),
            version: "9".into(),
            license: "MIT".into(),
            copyright: "Copyright (c) 2015 Vincent Prouillet".into(),
            text: "MIT License\n\nPermission is hereby granted, free of charge, to any person obtaining a copy of this software...".into(),
        },
        LicenseEntry {
            name: "argon2".into(),
            version: "0.5".into(),
            license: "MIT OR Apache-2.0".into(),
            copyright: "Copyright (c) 2021 RustCrypto Developers".into(),
            text: "MIT License\n\nPermission is hereby granted, free of charge, to any person obtaining a copy of this software...".into(),
        },
        LicenseEntry {
            name: "tracing".into(),
            version: "0.1".into(),
            license: "MIT".into(),
            copyright: "Copyright (c) 2019 Tokio Contributors".into(),
            text: "MIT License\n\nPermission is hereby granted, free of charge, to any person obtaining a copy of this software...".into(),
        },
        LicenseEntry {
            name: "instant-acme".into(),
            version: "0.4".into(),
            license: "Apache-2.0".into(),
            copyright: "Copyright (c) 2022 Instant Labs".into(),
            text: "Apache License\nVersion 2.0, January 2004\nhttp://www.apache.org/licenses/".into(),
        },
        LicenseEntry {
            name: "yara-x".into(),
            version: "0.4".into(),
            license: "BSD-3-Clause".into(),
            copyright: "Copyright (c) VirusTotal".into(),
            text: "BSD 3-Clause License\n\nRedistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met...".into(),
        },
        LicenseEntry {
            name: "prometheus".into(),
            version: "0.13".into(),
            license: "Apache-2.0".into(),
            copyright: "Copyright (c) TiKV Project Authors".into(),
            text: "Apache License\nVersion 2.0, January 2004\nhttp://www.apache.org/licenses/".into(),
        },
    ];

    Json(serde_json::json!({ "success": true, "data": entries }))
}

/// GET /api/system/licenses/frontend — returns JavaScript/frontend dependency license list.
///
/// In production this will read `frontend-licenses.json` generated by license-checker.
/// Currently returns a representative stub list.
pub async fn get_licenses_frontend(State(_state): State<AppState>) -> impl IntoResponse {
    let entries: Vec<LicenseEntry> = vec![
        LicenseEntry {
            name: "react".into(),
            version: "18.3.0".into(),
            license: "MIT".into(),
            copyright: "Copyright (c) Meta Platforms, Inc. and affiliates.".into(),
            text: "MIT License\n\nCopyright (c) Meta Platforms, Inc. and affiliates.\n\nPermission is hereby granted, free of charge, to any person obtaining a copy...".into(),
        },
        LicenseEntry {
            name: "vite".into(),
            version: "5.0.0".into(),
            license: "MIT".into(),
            copyright: "Copyright (c) 2019-present, Yuxi (Evan) You and Vite contributors".into(),
            text: "MIT License\n\nPermission is hereby granted, free of charge, to any person obtaining a copy...".into(),
        },
        LicenseEntry {
            name: "zustand".into(),
            version: "4.5.0".into(),
            license: "MIT".into(),
            copyright: "Copyright (c) 2019 Paul Henschel".into(),
            text: "MIT License\n\nPermission is hereby granted, free of charge, to any person obtaining a copy...".into(),
        },
        LicenseEntry {
            name: "@tanstack/react-query".into(),
            version: "5.0.0".into(),
            license: "MIT".into(),
            copyright: "Copyright (c) 2021-present Tanner Linsley".into(),
            text: "MIT License\n\nPermission is hereby granted, free of charge, to any person obtaining a copy...".into(),
        },
        LicenseEntry {
            name: "@tanstack/react-table".into(),
            version: "8.0.0".into(),
            license: "MIT".into(),
            copyright: "Copyright (c) 2016 Tanner Linsley".into(),
            text: "MIT License\n\nPermission is hereby granted, free of charge, to any person obtaining a copy...".into(),
        },
        LicenseEntry {
            name: "tailwindcss".into(),
            version: "3.4.0".into(),
            license: "MIT".into(),
            copyright: "Copyright (c) Tailwind Labs, Inc.".into(),
            text: "MIT License\n\nPermission is hereby granted, free of charge, to any person obtaining a copy...".into(),
        },
        LicenseEntry {
            name: "uplot".into(),
            version: "1.6.30".into(),
            license: "MIT".into(),
            copyright: "Copyright (c) 2021, Leon Sorokin".into(),
            text: "MIT License\n\nPermission is hereby granted, free of charge, to any person obtaining a copy...".into(),
        },
        LicenseEntry {
            name: "echarts".into(),
            version: "5.4.0".into(),
            license: "Apache-2.0".into(),
            copyright: "Copyright (c) Apache Software Foundation".into(),
            text: "Apache License\nVersion 2.0, January 2004\nhttp://www.apache.org/licenses/".into(),
        },
        LicenseEntry {
            name: "@svgdotjs/svg.js".into(),
            version: "3.2.0".into(),
            license: "MIT".into(),
            copyright: "Copyright (c) 2012-2022 Wout Fierens".into(),
            text: "MIT License\n\nPermission is hereby granted, free of charge, to any person obtaining a copy...".into(),
        },
        LicenseEntry {
            name: "@tiptap/react".into(),
            version: "2.2.0".into(),
            license: "MIT".into(),
            copyright: "Copyright (c) 2021 ueberdosis GmbH".into(),
            text: "MIT License\n\nPermission is hereby granted, free of charge, to any person obtaining a copy...".into(),
        },
        LicenseEntry {
            name: "date-fns".into(),
            version: "3.0.0".into(),
            license: "MIT".into(),
            copyright: "Copyright (c) 2021 Sasha Koss and Lesha Koss".into(),
            text: "MIT License\n\nPermission is hereby granted, free of charge, to any person obtaining a copy...".into(),
        },
    ];

    Json(serde_json::json!({ "success": true, "data": entries }))
}

/// GET /api/system/sbom — returns a CycloneDX JSON SBOM for download.
///
/// In production this file is generated at build time and served from disk.
/// This stub returns a minimal valid CycloneDX 1.4 document.
pub async fn download_sbom(State(_state): State<AppState>) -> impl IntoResponse {
    let sbom = serde_json::json!({
        "bomFormat": "CycloneDX",
        "specVersion": "1.4",
        "version": 1,
        "metadata": {
            "timestamp": chrono::Utc::now().to_rfc3339(),
            "component": {
                "type": "application",
                "name": "inside-operations",
                "version": env!("CARGO_PKG_VERSION")
            }
        },
        "components": []
    });

    let body = serde_json::to_string_pretty(&sbom).unwrap_or_default();

    Response::builder()
        .status(StatusCode::OK)
        .header(header::CONTENT_TYPE, "application/json")
        .header(
            header::CONTENT_DISPOSITION,
            "attachment; filename=\"io-sbom.json\"",
        )
        .body(Body::from(body))
        .unwrap_or_else(|_| StatusCode::INTERNAL_SERVER_ERROR.into_response())
}
