// ---------------------------------------------------------------------------
// Chart type metadata — name, category, description, pros/cons, usage notes
// Used by ChartTypePicker to populate the left list and right preview panel.
// ---------------------------------------------------------------------------

import type { ChartTypeId } from './chart-config-types'

export type ChartTier = 'initial' | 'mid' | 'late'
export type ChartLibrary = 'uPlot' | 'ECharts' | 'Plotly' | 'Custom' | 'TanStack'
export type ChartContext = 'console' | 'dashboard' | 'designer' | 'report'

export interface ChartDefinition {
  id: ChartTypeId
  name: string
  category: string
  tier: ChartTier
  library: ChartLibrary
  realTime: boolean | 'optional'
  description: string
  benefits: string[]
  downsides: string[]
  usage?: string
  /** If present, chart is only available in the listed contexts. Omit = available everywhere. */
  contexts?: ChartContext[]
}

export const CHART_DEFINITIONS: ChartDefinition[] = [
  // ── Time-Series Trends ──────────────────────────────────────────────────────
  {
    id: 1,
    name: 'Live Trend',
    category: 'Time-Series',
    tier: 'initial',
    library: 'uPlot',
    realTime: true,
    description: 'Auto-scrolling real-time trend showing current point values as they arrive. The chart continuously appends new data and scrolls left, discarding data that falls off the trailing edge. Up to 12 pens on a single axis let operators compare related variables side by side.',
    benefits: ['Always shows right now', 'Up to 12 pens — compare related variables', 'Configurable lookback window', 'Sub-second live updates'],
    downsides: ['Cannot review the past beyond the lookback window', 'Not useful for deep historical analysis'],
    usage: 'Group related variables onto one trend — inlet temperature, outlet temperature, and setpoint together; or feed flow, product flow, and recycle flow together. A 1–2 hour lookback suits most operator tasks; extend to 8–12 hours for shift-level monitoring. For process upsets, shrink the window to minutes to see the fast dynamics clearly.',
  },
  {
    id: 2,
    name: 'Historical Trend',
    category: 'Time-Series',
    tier: 'initial',
    library: 'uPlot',
    realTime: false,
    description: 'Fixed time range trend for archived data. User selects start/end time and the chart renders the full range. Resolution adjusts automatically as you zoom — wide windows show hourly averages, tight windows reveal raw sample-by-sample data.',
    benefits: ['Review any historical period', 'Zoom in to full raw resolution', 'Good for incident investigation'],
    downsides: ['Static — no live updates', 'Best used in Forensics module'],
    usage: 'Start with a wide window (days or weeks) to locate the event, then zoom in to the minutes surrounding an upset to read exact values and transition times. Compare the period before a process change to the period after by setting the time range to bracket the change date. Most useful alongside the Event Timeline for correlating alarms with measured process excursions.',
  },
  {
    id: 3,
    name: 'Multi-Axis Trend',
    category: 'Time-Series',
    tier: 'initial',
    library: 'uPlot',
    realTime: true,
    description: 'Multiple Y-axes for parameters with different engineering units sharing a synchronized time axis. Supports side-by-side axes (left/right) and vertically stacked panes. A synchronized crosshair spanning all axes makes it easy to read corresponding values at any moment in time.',
    benefits: ['Correlate different unit types (°C vs bar vs kg/h)', 'Synchronized crosshair', 'Stacked or side-by-side layouts'],
    downsides: ['More complex than a simple trend', 'Risk of axis crowding with many series'],
    usage: 'Assign variables with the same engineering units to a shared axis to preserve proportional comparison. Give each independently-scaled variable its own axis — for example, reactor temperature (°C) on the left, pressure (bar) on the right, and feed flow (kg/h) on a third axis. Use stacked layout when the variables have very different magnitudes that would visually compress each other. Limit to 4–5 axes before the chart becomes harder to read than two separate trends.',
  },
  {
    id: 4,
    name: 'Step Chart',
    category: 'Time-Series',
    tier: 'initial',
    library: 'uPlot',
    realTime: true,
    description: 'Horizontal-then-vertical step interpolation for discrete/digital values. A valve is either OPEN or CLOSED — never mid-transition. Rendering discrete states with a sloped line between them implies a smooth transition that does not exist and misrepresents the data.',
    benefits: ['Correct visualization for digital/discrete values', 'Shows exact state transition moments', 'ISA-compliant discrete state display'],
    downsides: ['Not appropriate for analog continuous variables'],
    usage: 'Use wherever a point has a finite number of named states: valve open/closed, pump running/stopped, compressor mode (auto/manual/standby), or any on/off permissive. Combine with a Live Trend or Multi-Axis Trend on the same pane to see how discrete state changes influence continuous process variables — for example, layering pump status below a pressure trend immediately shows whether pressure drops correlate with pump trips.',
  },
  {
    id: 16,
    name: 'Batch Comparison',
    category: 'Time-Series',
    tier: 'mid',
    library: 'uPlot',
    realTime: false,
    description: 'Multiple time-series from different time periods overlaid on a common relative time axis (elapsed time from batch start). Compare this batch against a golden batch — the best-performing historical run — to see exactly where and when the current process deviated.',
    benefits: ['Identifies batch-to-batch deviations', 'Aligns multiple runs to a common start point', 'Golden batch reference comparison with configurable label'],
    downsides: ['Requires batch-aware process', 'Historical data only'],
    usage: 'Select your golden batch (the reference run with the best yield or quality result) and overlay the current or recent batches against it. Label the reference series in Options → "Reference batch label" so operators know which run is the standard. Focus on the key quality-driving variables first — reactor temperature profile, pH trajectory, or dissolved oxygen curve depending on your process. Deviations from the golden batch shape in the first 20–30% of elapsed time often predict end-of-batch quality, making this chart useful for early intervention. Compare failed batches against the golden batch to identify which phase introduced the deviation.',
  },
  {
    id: 22,
    name: 'Stacked Area',
    category: 'Time-Series',
    tier: 'mid',
    library: 'uPlot',
    realTime: true,
    description: 'Line chart with colored fill below each series, stacked so total height represents the cumulative sum. Shows both the total and each component\'s contribution over time. The bottom series is the most readable; upper series show relative contribution rather than precise values.',
    benefits: ['Shows total + component breakdown simultaneously', 'Proportional and absolute stacking modes', 'Live or historical'],
    downsides: ['Hard to read when many series present', 'Upper series hard to read individually'],
    usage: 'Use absolute stacking to visualize total plant throughput broken down by unit or feed source — each colored band is one contributor and the top of the stack is the plant total. Use percentage stacking to show how the product mix or feed composition changes over time as a proportion of the total. Keep series count to 5 or fewer; beyond that the thin upper bands become unreadable. Place the most important or most variable contributor at the bottom where the absolute scale is clearest.',
  },

  // ── SPC ────────────────────────────────────────────────────────────────────
  {
    id: 24,
    name: 'Shewhart Control Chart',
    category: 'SPC',
    tier: 'mid',
    library: 'uPlot',
    realTime: false,
    description: 'The foundational SPC chart. Time-series with center line (process mean), UCL at +3σ, and LCL at -3σ. Automated Western Electric / Nelson rules flag pattern violations with highlighted markers — a single point outside the 3σ limits, or eight consecutive points on one side of the mean, are both signals that the process has changed.',
    benefits: ['Detects large sudden shifts (>2σ) immediately', 'Industry standard SPC chart', 'Automated rule violation flagging'],
    downsides: ['Insensitive to small sustained shifts (<1.5σ)', 'Assumes independent observations'],
    usage: 'Apply to any critical process parameter where you need to distinguish natural variation from a real process change — product quality measurements, yield per shift, catalyst activity, or utility consumption. Establish the control limits from a period of known-stable operation (at least 25–30 subgroups). Use Western Electric rules for standard chemical/refinery monitoring; switch to Nelson rules if you need tighter pattern detection. When a rule fires, investigate before adjusting — over-correction on false signals increases variance.',
  },
  {
    id: 29,
    name: 'CUSUM Chart',
    category: 'SPC',
    tier: 'late',
    library: 'uPlot',
    realTime: false,
    description: 'Cumulative sum of deviations from a target. Specifically designed to detect small sustained shifts (1σ or less) that Shewhart charts miss. A 0.5σ drift produces a steadily climbing line that eventually signals, where a Shewhart chart would show nothing for weeks.',
    benefits: ['Most sensitive to small sustained mean shifts', 'Amplifies persistent small deviations', 'Tabular decision criteria with configurable sensitivity'],
    downsides: ['Assumes independent observations', 'Not sensitive to large sudden shifts', 'Resets after signal'],
    usage: 'Apply to slow-drifting processes where early warning of gradual change matters most: catalyst deactivation, heat exchanger fouling, column tray efficiency, pump wear, or analyzer drift. Set the target to your process aim point (not the alarm limit). Use the default sensitivity settings to start — tighten them once you have experience with how the chart behaves on your specific variable. When the chart signals, the slope of the cumulative sum line indicates how long the drift has been occurring.',
  },
  {
    id: 30,
    name: 'EWMA Chart',
    category: 'SPC',
    tier: 'late',
    library: 'uPlot',
    realTime: false,
    description: 'Exponentially weighted moving average with adaptive control limits. More robust than Shewhart for autocorrelated or non-normal data — most continuous process measurements are autocorrelated (the current value depends on the previous value), which makes EWMA a better default than Shewhart for many process variables. Lambda controls the balance between sensitivity and noise rejection.',
    benefits: ['Handles autocorrelated data', 'Robust to non-normal distributions', 'Adjustable sensitivity via lambda'],
    downsides: ['Lambda tuning required for best results'],
    usage: 'Use EWMA as the default SPC chart for continuous process measurements like temperature, pressure, and flow — these are almost always autocorrelated, which inflates false alarm rates on a Shewhart chart. Start with the default lambda (0.2) and tighten it toward 0.05–0.1 for slow-drifting variables like catalyst activity or heat exchanger UA. Increase lambda toward 0.3–0.4 if you want it to behave more like a Shewhart chart that reacts quickly to step changes.',
  },

  // ── Statistical ─────────────────────────────────────────────────────────────
  {
    id: 13,
    name: 'XY Plot / Scatter',
    category: 'Statistical',
    tier: 'initial',
    library: 'ECharts',
    realTime: false,
    description: 'One process variable plotted against another (not time). Shows relationships and correlations — compressor discharge pressure vs. speed, heat exchanger effectiveness vs. throughput, reactor conversion vs. temperature. Each point is a moment in time; the cloud of points reveals the underlying process relationship. Density mode (auto or manual) bins the X/Y space and colors each bin by point density — essential when thousands of overlapping points make individual markers unreadable. Shows exactly where the process spends its time.',
    benefits: ['Reveals variable relationships and correlations', 'Operating envelope analysis', 'Color by time shows process evolution', 'Density mode shows operating mode clusters for high-point-count datasets', 'Configurable point opacity and size'],
    downsides: ['Historical data only', 'Requires meaningful X-Y pairing'],
    usage: 'Use to validate process models and operating envelopes: do your actual operating points follow the expected curve? Enable "Color by time" to see whether the relationship is drifting over weeks or months — a scatter cloud that has migrated across the chart indicates a process change such as fouling or catalyst deactivation. For large datasets (months of data), enable density mode: the chart divides the X/Y space into bins and colors each bin by the number of operating hours spent there. The darkest cells are your normal operating mode — any scatter points outside those cells are your excursions. To find the normal operating envelope, use a period of good operation as the baseline and overlay a suspect period to see which points fall outside the normal cloud. Combine with Regression to fit and quantify the relationship.',
  },
  {
    id: 19,
    name: 'Box Plot',
    category: 'Statistical',
    tier: 'mid',
    library: 'ECharts',
    realTime: false,
    description: 'Distribution summary showing median, Q1, Q3, whiskers at 1.5×IQR, and individual outlier points. Ideal for side-by-side comparison of the same variable across shifts, time periods, or operating modes. The box width represents the middle 50% of values — a wide box means high variability, a narrow box means tight control. Horizontal orientation is available when category names are long.',
    benefits: ['Compact comparison of multiple distributions', 'Shows median, spread, and outliers', 'Easy shift/mode comparison', 'Optional individual point overlay and notched confidence intervals', 'Horizontal orientation for long category names'],
    downsides: ['Loses distribution shape detail (use Histogram for that)', 'Only 5 summary statistics per group'],
    usage: 'Compare process performance across shifts (day/evening/night), operators, weeks, or before/after a process change. A box that shifts upward means the median has moved; a box that grows taller means variability increased. Enable "Show individual points" to see every data point alongside the box — useful for identifying whether outliers are isolated incidents or a cluster. Enable "Notched boxes" to visually compare medians: non-overlapping notches indicate statistically significant difference. Outlier points beyond the whiskers are your worst-case excursions — investigate those specific time periods. Use horizontal orientation when comparing many categories with long names — the labels read clearly on the left side.',
  },
  {
    id: 20,
    name: 'Histogram / Violin Plot',
    category: 'Statistical',
    tier: 'mid',
    library: 'ECharts',
    realTime: false,
    description: 'Two display modes in one chart type. Histogram mode: frequency distribution dividing a variable\'s range into equal-width bins. Reveals the full distribution shape — normal, right-skewed, bimodal, or otherwise. Violin mode: kernel density estimate mirrored symmetrically to form the characteristic violin shape, with box plot statistics (median, Q1/Q3, whiskers) overlaid inside. The violin shows details that a box plot hides: a bimodal violin (two bulges) immediately reveals two operating modes that a box plot would show as just a wide IQR. Both modes support horizontal orientation.',
    benefits: ['Histogram mode shows full distribution shape', 'Violin mode reveals bimodal distributions that box plots hide', 'Normal curve overlay (histogram mode)', 'Optional capability stats (Cp/Cpk) with configurable USL/LSL', 'Horizontal orientation for both modes'],
    downsides: ['One variable at a time', 'Bin count choice affects histogram appearance', 'Cannot compare distributions side-by-side (use Box Plot for multi-group comparison)'],
    usage: 'Histogram: Start with a large time range (1–3 months) to capture the full operating distribution. Enable the normal overlay to see how far your process deviates from a normal curve. If you see a bimodal shape, split the data by operating mode and histogram each subset separately. Enable Cp/Cpk to calculate process capability. Violin: use when you want the compact comparison of a box plot combined with the shape detail of a histogram. Two bulges in the violin = two operating modes; this is the key insight the box plot misses. Horizontal orientation works well when embedding alongside a list of equipment names.',
  },
  {
    id: 25,
    name: 'Regression / Trendline',
    category: 'Statistical',
    tier: 'mid',
    library: 'uPlot',
    realTime: false,
    description: 'Fitted mathematical curve (linear, polynomial, exponential) overlaid on scatter or time-series data. Shows trend direction and rate with equation, R², and confidence intervals. R² (0–1) tells you what fraction of the variation the model explains — 1.0 is a perfect fit, 0 means no relationship.',
    benefits: ['Projects future values mathematically', 'Quantifies degradation rate', 'Confidence intervals show fit uncertainty'],
    downsides: ['Cannot extrapolate reliably far beyond data range', 'Assumes chosen model shape matches reality'],
    usage: 'Use on time-series data to quantify and project equipment degradation: heat exchanger UA (heat transfer coefficient over time), compressor efficiency, pump head, catalyst activity, filter differential pressure. An exponential model fits most fouling and deactivation curves better than a straight line. Once the trendline is fitted, extend it forward in time to estimate when the variable will breach an operating limit — this gives a projected maintenance date. If R² is below 0.6, the degradation signal is being masked by process variability and a longer data range or smoother data may be needed.',
  },
  {
    id: 26,
    name: 'Correlation Matrix',
    category: 'Statistical',
    tier: 'mid',
    library: 'ECharts',
    realTime: false,
    description: 'Square grid showing pairwise correlation coefficients between multiple variables, color-coded from strong negative (blue) to zero (white) to strong positive (red). The fastest way to screen dozens of variables for relationships — a single matrix replaces hundreds of individual scatter plots.',
    benefits: ['Shows all pairwise correlations at once', 'Quickly identifies leading indicators', 'Optional hierarchical clustering reorders variables to group related ones'],
    downsides: ['Practical limit ~20–30 variables', 'Only shows linear correlation — non-linear relationships may appear weak'],
    usage: 'Add all potentially relevant process variables (10–25 is ideal) for a time period that spans normal variation. Look for strong correlations (dark red or blue cells) between quality outcomes and upstream process conditions — these are your candidate control handles. Enable clustering so related variables group together, which reveals blocks of co-moving variables (often corresponding to physical sub-systems). Click any interesting cell to open the full XY scatter plot for that pair and examine whether the relationship is consistent or changes across operating modes. Use Spearman correlation when your data contains outliers or obvious non-linear relationships.',
  },
  {
    id: 31,
    name: 'Probability Plot',
    category: 'Statistical',
    tier: 'late',
    library: 'Plotly',
    realTime: false,
    description: 'Quantile-quantile (Q-Q) plot comparing actual data against a theoretical distribution. If data follows the distribution, points fall on a straight reference line. An S-curve indicates heavy tails; a bend at one end indicates skewness; a step indicates a mixture of two populations.',
    benefits: ['Precise normality assessment', 'Tests specific distribution families', 'Critical prerequisite for SPC validity'],
    downsides: ['Less intuitive than histogram'],
    usage: 'Run this before setting up a Shewhart or EWMA control chart — SPC control limits are only valid if the underlying distribution matches your assumption (usually normal). If the points curve away from the reference line, try lognormal (common for concentration, particle size, and response time data) or Weibull (common for time-to-failure and strength data). A good fit on the probability plot means your SPC control limits will have the expected false-alarm rate. A poor fit means the limits will be either too tight (too many false alarms) or too wide (real signals missed).',
  },

  // ── Categorical ─────────────────────────────────────────────────────────────
  {
    id: 5,
    name: 'Bar / Column Chart',
    category: 'Categorical',
    tier: 'initial',
    library: 'ECharts',
    realTime: 'optional',
    description: 'Vertical (column) or horizontal (bar) charts for categorical comparisons. Supports grouped, stacked, and 100%-stacked variants. A combination mode overlays a secondary line series (e.g., running total or target) on the same chart area. Error bars show ±σ or min/max spread per bar. Bar length encodes magnitude directly, making precise comparison easier than pie charts for most audiences.',
    benefits: ['Precise magnitude comparison', 'Grouped, stacked, and 100% stacked variants', 'Combination mode: overlay a line series on bars (e.g., actual + target)', 'Error bars show spread or uncertainty per category', 'Horizontal or vertical orientation', 'Can auto-refresh for live dashboards'],
    downsides: ['Not for time-series with many data points', 'Use Pareto instead when you need sorted ranking'],
    usage: 'Use vertical columns for comparing a small number of categories (production rates by unit, throughput by product grade). Use horizontal bars when category names are long or when you have many categories — labels fit more naturally to the left of a horizontal bar. Group bars side by side to compare the same metric across multiple time periods or operating modes. Stack bars to show how each category is composed (e.g., planned vs. actual vs. lost production by unit). Use 100% stacking to show proportional breakdown regardless of total size. Enable combo mode and assign a second point as the line to overlay a target or cumulative total. When categories have a natural ranking from highest to lowest, switch to a Pareto chart instead.',
  },
  {
    id: 6,
    name: 'Pie / Donut Chart',
    category: 'Categorical',
    tier: 'initial',
    library: 'ECharts',
    realTime: 'optional',
    description: 'Circular proportional chart. Limited to approximately 7 slices; additional values bucketed into "Other." Donut variant has a center hole for embedding a total or summary label. Slice area is proportional to value, making large differences obvious but small differences hard to compare.',
    benefits: ['Instantly communicates "parts of a whole"', 'Configurable center label in donut variant', 'Familiar to all audiences'],
    downsides: ['Poor for comparing similarly-sized slices', 'Limited to ~7 categories', 'Bar charts are more precise'],
    usage: 'Best suited to high-level composition snapshots where the audience just needs "roughly what fraction" — plant feed mix by crude source, production split by product grade, or energy consumption by major consumer. Keep to 4–6 meaningful slices; consolidate everything else into "Other." If two or more slices are close in size and the exact difference matters, switch to a bar chart where lengths are easier to compare accurately. The donut variant works well on dashboards where the center label can show the total or a key KPI.',
  },
  {
    id: 23,
    name: 'Bullet Chart',
    category: 'Categorical',
    tier: 'mid',
    library: 'ECharts',
    realTime: 'optional',
    description: 'Compact bar showing actual value against a target marker, with shaded background ranges for qualitative performance levels (poor/satisfactory/good). One-fifth the screen space of a gauge for the same information — a column of 8–10 bullet charts fits comfortably on a single dashboard. Supports both horizontal (default) and vertical orientations.',
    benefits: ['Very space-efficient KPI display', 'Shows actual vs target in one view', 'Qualitative bands for context', 'Horizontal (default) or vertical orientation'],
    downsides: ['Less intuitive to non-technical audiences than a gauge'],
    usage: 'Stack multiple bullet charts vertically for a compact management dashboard — one row per KPI (rate, yield, energy intensity, quality, uptime). Set the target marker to your production plan, budget, or SLA value. Define 2–3 background bands: a narrow green band for the acceptable range, a wider yellow band for marginal performance, and the remaining space in red. The bar instantly shows whether you are on target, how far off you are, and which qualitative zone you are in — all without reading a number. Use vertical orientation for a column-oriented layout where bullets stack side by side.',
  },
  {
    id: 18,
    name: 'Pareto Chart',
    category: 'Categorical',
    tier: 'mid',
    library: 'ECharts',
    realTime: false,
    description: 'Bar chart sorted by frequency/impact (descending) with overlaid cumulative percentage line. Three ranking modes: count (alarm annunciations), standing time (total active duration — the key ISA-18.2 nuisance alarm KPI), and rate (alarms per hour). A separate priority distribution mode shows the split of alarms by priority level (HH/H/M/L) against the ISA-18.2 recommended limits. Supports horizontal orientation for long tag names.',
    benefits: ['Enforces sorted ranking (most impactful first)', 'Cumulative line shows 80/20 threshold visually', 'Standard ISA-18.2 analysis tool', 'Standing time mode surfaces nuisance alarms that stay active for hours', 'Priority distribution mode checks ISA-18.2 priority balance targets', 'Horizontal orientation for long tag names'],
    downsides: ['Historical data only', 'Requires event/count data, not continuous measurements'],
    usage: 'Run this monthly as part of ISA-18.2 alarm management reviews. For bad actor identification, use count mode — the left-most bars are the tags that fired most. For nuisance alarm identification, switch to standing time mode — an alarm that stays active for 12 hours without being cleared is a nuisance even if it only fired once. The cumulative line crossing 80% shows you exactly how many tags you need to address to resolve the majority of the alarm load. Use priority distribution mode to check whether your alarm configuration follows ISA-18.2 guidance: less than 5% Critical and less than 15% High by annunciation count. Switch to horizontal orientation when tag names are too long to fit under vertical bars.',
  },
  {
    id: 21,
    name: 'Waterfall Chart',
    category: 'Categorical',
    tier: 'mid',
    library: 'ECharts',
    realTime: false,
    description: 'Sequential bar chart showing how positive and negative contributions accumulate to a total. Each bar starts where the previous ended with connecting lines showing the running total. Green bars add to the total, red bars subtract — the final bar is the net result. Supports horizontal orientation for long step names.',
    benefits: ['Shows where gains and losses occur in a sequence', 'Running total always visible', 'Clear positive/negative contribution coding', 'Horizontal orientation for long step names'],
    downsides: ['Not for time-series with many points', 'Requires pre-defined step sequence'],
    usage: 'Use to visualize energy and material balances: start with total energy input, then show each loss category (flue gas, radiation, blowdown, unaccounted) as negative bars, and end at net useful output. Also effective for pressure drop analysis across a piping system — each segment is a bar, making it obvious which section contributes the most to total pressure loss. For production accounting, start at rated capacity, then show deductions (planned downtime, unplanned downtime, rate limitations, quality losses) to arrive at actual production. Keep steps to 8 or fewer for readability. Use horizontal orientation when step names are long descriptive labels that read more clearly on the left.',
  },

  // ── Flow / Hierarchy ────────────────────────────────────────────────────────
  {
    id: 27,
    name: 'Sankey Diagram',
    category: 'Flow / Hierarchy',
    tier: 'late',
    library: 'ECharts',
    realTime: 'optional',
    description: 'Flow diagram where link widths are proportional to flow quantity. Shows how a total splits, merges, and routes through a system — energy from furnaces through heat exchangers to products. At a glance, the widest links are the dominant flows and the thinnest links are the minor ones.',
    benefits: ['Width proportionality makes largest flows obvious', 'Shows branching and merging flows', 'Can refresh on interval for live balance'],
    downsides: ['Requires manual node/link definition', 'Complex to set up for large networks'],
    usage: 'Define the nodes (sources, intermediate points, and sinks) and draw links between them. Assign each link to a process point so the width updates automatically. Common applications: plant energy balance (fuel gas → fired heaters → process duties → steam → losses), crude split across distillation units, or water network flows. Configure an auto-refresh interval for a live energy dashboard. For the initial setup, start with the highest-level flows and add detail in sub-diagrams rather than trying to show everything in one diagram.',
  },
  {
    id: 28,
    name: 'Treemap',
    category: 'Flow / Hierarchy',
    tier: 'late',
    library: 'ECharts',
    realTime: false,
    description: 'Nested rectangles where area is proportional to value within a hierarchy. Color encodes a second dimension (alarm count with severity color). Instantly shows where problems are concentrated — the largest, darkest rectangle in a plant-wide alarm treemap is your worst-affected area.',
    benefits: ['Preserves hierarchical structure (plant > area > unit > tag)', 'Area makes magnitude instantly comparable', 'Drill-down for hierarchy navigation'],
    downsides: ['Complex hierarchical data required', 'Hard to read with many same-sized items'],
    usage: 'Structure the hierarchy to match your plant: Plant → Process Area → Unit → Tag. Set rectangle area to alarm count and color to worst active severity (grey = normal, yellow = low, orange = high, red = high-high). At a glance, the largest red rectangle is the unit with the most severe alarm load — click to drill down. Also useful for production loss analysis (area = lost production hours, color = loss category) or maintenance backlog (area = outstanding work orders, color = priority). The treemap is most useful when the values span a wide range; if all items are similar in size, a bar chart is clearer.',
  },
  {
    id: 32,
    name: 'Funnel Chart',
    category: 'Flow / Hierarchy',
    tier: 'late',
    library: 'ECharts',
    realTime: 'optional',
    description: 'Stacked trapezoids of decreasing width representing progressive reduction through sequential stages. Width proportional to value makes drop-off rates between stages immediately visible — a dramatic narrowing between two stages is where the bottleneck or attrition occurs.',
    benefits: ['Shows stage-by-stage attrition clearly', 'Conversion rates between stages', 'Works for any sequential pipeline'],
    downsides: ['Only for strictly sequential processes', 'Not for branching flows (use Sankey)'],
    usage: 'Apply to any process with a defined pipeline of sequential stages where items can drop out at each step. Work order management: raised → screened → approved → planned → scheduled → in-progress → closed. MOC process: initiated → risk assessed → approved → implemented → verified → closed. Inspection pipeline: scheduled → assigned → completed → reviewed → filed. Enable conversion percentage labels between stages to highlight which stage has the largest drop-off — that is where process improvement will have the most impact.',
  },
  {
    id: 33,
    name: 'Radar Chart',
    category: 'Flow / Hierarchy',
    tier: 'late',
    library: 'ECharts',
    realTime: 'optional',
    description: 'Multi-axis polygon where each axis represents a different attribute. Data values plotted on each axis connected to form a filled polygon. Compares equipment health across dimensions (vibration, temperature, efficiency, runtime, maintenance age) — a perfectly balanced polygon means all attributes are equal; a lopsided shape points to the weak attribute.',
    benefits: ['Multi-attribute profiles at a glance', '"Shape" of profile instantly recognizable', 'Highlights imbalanced performance'],
    downsides: ['Hard to read with more than 8 axes', 'Axis scale differences require normalization'],
    usage: 'Normalize all axes to a 0–100 scale where 100 is perfect health or on-target performance and 0 is the worst acceptable state before action. Use 4–7 axes — common choices for rotating equipment: vibration severity, bearing temperature, efficiency vs. design, hours since last maintenance, and lubrication status. Overlay multiple pieces of the same equipment type to compare their health profiles side by side. For operating mode comparison, each polygon represents one mode (summer/winter, light feed/heavy feed) and the shape shows which KPIs change between modes and which stay constant.',
  },

  // ── Industrial Indicators ───────────────────────────────────────────────────
  {
    id: 7,
    name: 'KPI Card',
    category: 'Industrial',
    tier: 'initial',
    library: 'Custom',
    realTime: true,
    description: 'Single large value display with label, trend indicator (up/down arrow), threshold coloring, and optional embedded sparkline. The "big number" widget for dashboards — readable from across a control room.',
    benefits: ['Instantly readable from across the room', 'Threshold coloring with alarm states', 'Optional sparkline shows recent trend', 'Live updates'],
    downsides: ['Only shows one value', 'No time-series context without sparkline'],
    usage: 'Reserve KPI Cards for the 5–10 metrics that matter most at shift level: current throughput rate, cumulative production vs. plan, plant availability, energy intensity, key quality index. Set warning threshold where an operator should investigate and critical threshold where action is required. Enable the embedded sparkline to show the last 2–4 hours of trend direction — the combination of current value + color + sparkline arrow gives a complete status picture at a glance without opening any other view.',
    contexts: ['dashboard', 'designer', 'report'],
  },
  {
    id: 8,
    name: 'Gauge',
    category: 'Industrial',
    tier: 'initial',
    library: 'ECharts',
    realTime: true,
    description: 'Circular radial gauge showing a single value against a range with colored threshold zones. Maps directly to the physical instrument analogy — operators who came up through the field recognize a gauge face immediately and can read it without training.',
    benefits: ['Familiar physical instrument metaphor', 'Colored threshold zones (green/yellow/red)', 'Live needle updates'],
    downsides: ['Large screen footprint for one value', 'Less space-efficient than Bullet Chart'],
    usage: 'Use for variables where the physical instrument metaphor adds clarity: vessel pressure (like a pressure gauge), tank level (like a sight glass), motor current (like an ammeter), or compressor speed. Set the full engineering range — from absolute zero or minimum possible value to the physical maximum — not just the alarm range. Compress the scale to only show the alarm range and the needle spends all its time in one spot, making it useless. Define 2–3 colored zones: a green normal operating band, a yellow caution zone, and a red alarm zone.',
  },
  {
    id: 9,
    name: 'Sparkline',
    category: 'Industrial',
    tier: 'initial',
    library: 'uPlot',
    realTime: true,
    description: 'Miniature inline trend chart with no axes, no labels, no interactive features. Embedded in table cells, KPI cards, and list views. Answers only one question — "which direction is this going?" — in the smallest possible space.',
    benefits: ['Extremely compact — minimal screen space', 'No visual clutter', 'Live updates'],
    downsides: ['No scale context', 'Cannot read specific values'],
    usage: 'Embed inside a KPI Card to show the recent history behind the headline number — is this value currently rising, falling, or stable? Use in data table cells where you need one column to add trend context without taking up the width of a full chart. A 1–2 hour lookback is appropriate for shift-level monitoring; extend to 8 hours if you want to show full-shift direction. Since there is no scale, sparklines communicate shape and direction only — pair them with the current value number so the reader has both context and precision.',
    contexts: ['dashboard', 'designer', 'report'],
  },
  {
    id: 10,
    name: 'Analog Bar Indicator',
    category: 'Industrial',
    tier: 'initial',
    library: 'Custom',
    realTime: true,
    description: 'ISA-101 "moving analog indicator" — segmented zone bar with moving pointer. Shows value position relative to operating limits, alarm thresholds, and setpoint in a compact linear format. Only the zone containing the current value is highlighted, making the current status immediately clear without reading a number.',
    benefits: ['ISA-101 compliant', 'Shows threshold position clearly', 'Optional setpoint marker', 'Horizontal or vertical'],
    downsides: ['Only for analog variables with defined zones', 'Not for physical level measurement (use Fill Gauge)'],
    usage: 'Use for any continuous process variable where you want the operator to see not just the value but its position within the operating envelope: flow controllers, temperature loops, pressure regulators. Define the full engineering range (minimum to maximum possible value) as the scale, then mark the normal operating band, caution zones, and alarm limits. Add a setpoint marker when the variable is under automatic control so operators can instantly see the gap between setpoint and process value. Mount vertically to mimic the orientation of a traditional panel instrument, or horizontally to fit a compact dashboard layout.',
    contexts: ['dashboard', 'designer', 'report'],
  },
  {
    id: 11,
    name: 'Fill Gauge',
    category: 'Industrial',
    tier: 'initial',
    library: 'Custom',
    realTime: true,
    description: 'Level indicator showing physical capacity as a continuous fill. A 62% value fills 62% of the gauge, making the fill height physically proportional to the actual content level. Supports vessel overlay mode (fills a custom equipment shape) and standalone bar mode.',
    benefits: ['Direct physical metaphor for tank/vessel levels', 'Fill color follows alarm state', 'Works as vessel overlay on graphics'],
    downsides: ['Only for physical levels (volume, mass)', 'Not for analog process variables (use Analog Bar)'],
    usage: 'Use for any measurement that represents a physical quantity inside a vessel: storage tanks (m³, barrels, tonnes), reactors, separators, surge drums, silos, and lagoons. Set the scale to actual engineering units (e.g., 0–5000 m³ or 0–100%) and configure the alarm thresholds to match your high-high/high/low/low-low alarm setpoints — the fill color will automatically shift to match the alarm state. In the Designer, use vessel overlay mode to place the fill inside a drawn or imported vessel shape on your P&ID graphic, so the level appears to fill the actual vessel outline.',
    contexts: ['dashboard', 'designer', 'report'],
  },
  {
    id: 12,
    name: 'Alarm Indicator',
    category: 'Industrial',
    tier: 'initial',
    library: 'Custom',
    realTime: true,
    description: 'ISA-101 priority-coded alarm indicator placed near equipment. Triple redundant coding (shape + color + text) ensures the priority is readable even by colorblind operators. The indicator is completely invisible when no alarm is active — it only occupies visual space when it matters.',
    benefits: ['ISA-101 compliant triple coding', 'Colorblind accessible', 'Single or aggregate mode', 'Flashes for unacknowledged alarms'],
    downsides: ['No trend context — point indicator only'],
    usage: 'Place directly adjacent to or inside an equipment shape on a process graphic so operators can see at a glance which pieces of equipment have active alarms. Use single-point mode for one alarm tag per indicator. Use aggregate mode to summarize all alarms on a piece of equipment (or an entire unit) into one indicator showing the worst active priority — this is the recommended approach for high-level overview graphics. The indicator flashes when an alarm is unacknowledged and stays lit (solid) once acknowledged but still active. When all alarms return to normal, the indicator disappears entirely so it does not distract the operator.',
    contexts: ['dashboard', 'designer'],
  },

  // ── Heatmap ─────────────────────────────────────────────────────────────────
  {
    id: 17,
    name: 'Heatmap',
    category: 'Heatmap',
    tier: 'mid',
    library: 'ECharts',
    realTime: 'optional',
    description: 'Two display modes in one chart type. Matrix mode: X/Y grid where color intensity represents value magnitude at each cell intersection — alarm frequency by hour-of-day vs. day-of-week, or any other 2D categorical breakdown. Calendar mode: ECharts native calendar layout — rows = weeks, columns = days of the week, each cell = one calendar day colored by its aggregate value. Calendar mode reveals day-of-year patterns: alarm frequency calendar, downtime days, production performance by day, safety incident calendar.',
    benefits: ['Reveals 2D patterns invisible in trends', 'Matrix mode for hour×day or any X×Y breakdown', 'Calendar mode shows day-of-year patterns across full months', 'Configurable color scale'],
    downsides: ['Requires categorical X and Y axes (matrix) or date data (calendar)', 'Color scale choice affects perception'],
    usage: 'Matrix mode: The most powerful application is alarm pattern analysis — set X to hour of day (0–23) and Y to day of week to immediately identify systematic triggers. Use for temperature distribution across a spatial grid where rows and columns represent physical positions. Calendar mode: configure a year and the chart shows a full 52-week calendar with each day\'s aggregate value as its color. Immediately reveals: is this alarm worse in winter? Which months had the most downtime days? Did the process change in March actually reduce the alarm rate? The calendar grid makes date-based seasonality and incident clustering immediately obvious.',
  },

  // ── Event / Timeline ─────────────────────────────────────────────────────────
  {
    id: 14,
    name: 'Event Timeline',
    category: 'Event',
    tier: 'initial',
    library: 'Custom',
    realTime: true,
    description: 'Horizontal timeline showing events, alarms, and state changes as colored bars and markers. Multiple rows for different sources. A synchronized crosshair connects the event timeline with adjacent trend charts so you can move through time and see exactly which process values were active when each event occurred.',
    benefits: ['Correlated with trend charts via synchronized cursor', 'Alarm and event history visualization', 'Duration bars show how long each alarm was active', 'Configurable priority filter (HH/H/M/L)'],
    downsides: ['Dense data requires filtering', 'Not for continuous measurement trends'],
    usage: 'Place the Event Timeline directly below a multi-pen trend in an investigation layout. Start with all alarms visible to get the full picture, then filter to High and High-High priority to remove noise. Enable duration bars to see how long each alarm was active — a very short duration means it was a momentary transient, while long durations indicate sustained process problems. Use the synchronized cursor to step from one alarm event to the corresponding moment on the trend and read the exact process conditions at the time. Look for sequences: does a low-flow alarm always precede a high-temperature alarm? That sequence tells you the failure mode.',
  },

  // ── Tabular ──────────────────────────────────────────────────────────────────
  {
    id: 15,
    name: 'Data Table',
    category: 'Tabular',
    tier: 'initial',
    library: 'TanStack',
    realTime: true,
    description: 'Full-featured data table with sorting, filtering, conditional formatting, and real-time cell updates. Handles very large datasets without slowing down — suitable for point lists, event logs, and any tabular data that needs precise reading of individual values.',
    benefits: ['Handles 100K+ rows without slowing down', 'Sortable, filterable columns', 'Real-time cell updates', 'Conditional formatting'],
    downsides: ['No trend context', 'Text-heavy — not for at-a-glance monitoring'],
    usage: 'Use as a point summary table: add each monitored point as a column and show current value, quality status, and last update time. Sort by value to quickly find the highest or lowest reading across all points. Apply conditional formatting to color cells red when a value is outside limits — the table becomes a compact alarm summary. For event and alarm logs, sort by timestamp descending so the most recent events appear first and the table auto-scrolls as new events arrive. Filter by tag name or description to quickly locate specific points within a large point list.',
  },

  // ── New chart types (ids 35–39) ─────────────────────────────────────────────
  {
    id: 35,
    name: 'State Timeline',
    category: 'Industrial',
    tier: 'initial',
    library: 'Custom',
    realTime: true,
    description: 'Shows discrete equipment states as colored bands over time. Multiple equipment items share a synchronized time axis — each row fills with color based on the current state of that equipment. At a glance, you can see every compressor, every valve, every pump: when it was running, idle, tripped, or in maintenance, for the entire selected time window. Distinct from Event Timeline (which shows point-in-time events as markers): State Timeline shows the continuous state at every moment.',
    benefits: [
      'Shows state history for multiple equipment items simultaneously',
      'Synchronized with adjacent trend charts via shared time cursor',
      'Simultaneous trips visible as a vertical boundary crossing multiple rows',
      'Configurable state labels and colors per value',
    ],
    downsides: ['Only for discrete/digital points, not continuous analog values'],
    usage: 'Place directly above or below a trend chart in an investigation layout. Assign the compressors, pumps, or valves relevant to the unit under investigation. Color running states green and fault states red. A vertical boundary crossing multiple rows simultaneously means a group trip — look at the trend chart at that exact moment to see the process conditions. Use to answer "how long was Unit 3 actually down between midnight and 6 AM?" with a precise visual answer rather than reading through an alarm log.',
  },
  {
    id: 36,
    name: 'Scorecard Table',
    category: 'Tabular',
    tier: 'mid',
    library: 'TanStack',
    realTime: true,
    description: 'Multi-KPI table where each cell is individually color-coded green/yellow/red against configurable thresholds. Rows are either time periods (current shift, last shift, this week) or parallel assets (Unit A, Unit B, Unit C). Each column is a KPI point. At a glance, you can see which KPIs are on target and which are marginal across multiple time periods or units simultaneously.',
    benefits: [
      'Per-cell threshold coloring — each KPI has its own green/yellow/red limits',
      'Rows can be time periods (shift comparison) or parallel assets (unit comparison)',
      'Aggregates: average, last, max, or min over each period',
      'Live refresh on configured interval',
    ],
    downsides: ['Aggregated view only — not for reading raw values at specific timestamps'],
    usage: 'The shift handover scorecard: one row per shift (Day/Evening/Night), one column per KPI (throughput rate, yield %, energy intensity, OEE, alarm count). Set green thresholds to your plan values and yellow to 5–10% off plan. The outgoing shift supervisor can see at a glance which KPIs they hit, which were marginal, and which failed. The asset comparison scorecard: one row per parallel unit (Compressor A/B/C), one column per health metric — immediately shows which unit is underperforming.',
    contexts: ['dashboard', 'designer', 'report'],
  },
  {
    id: 37,
    name: 'Parallel Coordinate Plot',
    category: 'Statistical',
    tier: 'mid',
    library: 'ECharts',
    realTime: false,
    description: 'Each process variable is a vertical axis arranged side by side. Each observation — a batch run, a shift, or a time bucket — becomes a line connecting all axes at its values. Every line in the plot is one production run or time period. Lines that cross or deviate from the main cluster are the outliers; their color shows when they occurred or which variable is the cause.',
    benefits: [
      'Shows all process variables for every batch/shift simultaneously',
      'Outlier observations stand out as crossing lines',
      'Color by time reveals drifts across campaigns',
      'Up to 12 simultaneous process variables',
    ],
    downsides: ['Dense with many observations — opacity and filtering are essential', 'Requires common time window or batch alignment'],
    usage: 'Add all key process variables for a unit: temperatures, pressures, flows, compositions, and quality outcomes. Use shift buckets to show 3 months of shift-level data — each line is one shift. The main cluster of lines represents normal operation. Lines that cross through the cluster or fall outside it are your anomalous shifts. Click a line to highlight it and identify the specific shift. Use color-by-time to see whether the cluster is drifting — a gradual migration over weeks indicates a process change.',
  },
  {
    id: 38,
    name: 'X-bar/R & X-bar/S Chart',
    category: 'SPC',
    tier: 'mid',
    library: 'uPlot',
    realTime: false,
    description: 'Subgroup SPC chart with two synchronized panels. The top panel tracks subgroup means (X-bar) — whether the process center is shifting. The bottom panel tracks subgroup spread: either range (R chart, for subgroups of 2–10) or standard deviation (S chart, for larger subgroups). Both panels must be in control for the process to be considered stable. A point out of control on the R or S chart means variability has changed; the X-bar panel cannot be interpreted until spread is controlled. Dual subgrouping mode: assign one point for time-based subgrouping (n consecutive readings per subgroup), or assign multiple points for spatial subgrouping (multiple instruments at different physical positions).',
    benefits: [
      'Simultaneously monitors both process centering and process spread',
      'More statistically efficient than individuals charts for batch/subgroup data',
      'Western Electric and Nelson rule violation detection',
      'Dual subgrouping: time-based (1 point + n) or spatial (multiple instruments)',
    ],
    downsides: ['Requires subgroup data (or historian data that will be aggregated into subgroups)', 'Assumes rational subgroups'],
    usage: 'Assign one point and set subgroup size n for time-based subgrouping: n consecutive readings form one subgroup (e.g., 5 readings per shift = one subgroup per shift). Assign multiple instruments measuring the same property for spatial subgrouping: each timestamp all assigned instruments form one subgroup — ideal for reactor thermocouples or parallel flowmeters. Use X-bar/R when n ≤ 10; switch to X-bar/S for n > 10. Before trusting the X-bar chart, confirm the R or S chart is in control.',
  },
  {
    id: 39,
    name: 'Attribute Control Chart',
    category: 'SPC',
    tier: 'late',
    library: 'ECharts',
    realTime: false,
    description: 'Statistical process control chart for count and proportion data. Four variants: p-chart (fraction defective, variable sample size), np-chart (count defective, fixed sample size), c-chart (defect count per unit, fixed sample), and u-chart (defects per unit, variable sample). Control limits are derived from the binomial distribution (p/np) or Poisson distribution (c/u) — not from the normal distribution used by Shewhart charts. When sample size varies, the control limits form a staircase profile.',
    benefits: [
      'Correct statistical model for count and proportion data',
      'All four standard attribute chart variants in one chart type',
      'Staircase UCL/LCL for variable sample sizes (p and u charts)',
      'Western Electric rule violation detection',
    ],
    downsides: ['Count data only — not for continuous measurements', 'Requires at least 25–30 subgroups to estimate the process rate reliably'],
    usage: 'Use p-chart when tracking the proportion of items that fail inspection and sample size changes from period to period. Use np-chart when sample size is constant and operators prefer raw defect counts. Use c-chart for products where you count total defects per item (not just pass/fail) — the c-chart captures severity that p-chart misses. Use u-chart when the inspection area or count of units varies per period, such as defects per square meter of coated surface.',
  },

  // ── 3D ──────────────────────────────────────────────────────────────────────
  {
    id: 34,
    name: '3D Surface / Contour',
    category: '3D',
    tier: 'late',
    library: 'Plotly',
    realTime: false,
    description: 'Three-dimensional surface or 2D contour projection showing how a response variable (Z) changes across two inputs (X, Y). Interactive 3D rotation, zoom, and pan. The ridge or valley on the surface is your optimal operating region — the combination of X and Y that maximizes or minimizes Z.',
    benefits: ['Shows response surface across two independent variables', 'Interactive 3D rotation', 'Identifies optimal operating regions visually'],
    downsides: ['Needs structured X/Y/Z dataset', 'No live updates'],
    usage: 'Use to visualize process optimization results: how yield varies with reactor temperature and pressure, how energy consumption changes with throughput and feed temperature, or how product quality responds to two key control variables. The data can come from a designed experiment (planned variation of X and Y) or from historical operating data spanning a range of conditions. The contour (top-down) view is often more useful than the 3D surface for identifying operating targets — the contour lines show regions of equal response and make it easy to draw the optimal operating window. Pair with an XY scatter showing where your actual operating points sit relative to the optimal region.',
  },
]

export const CHART_CATEGORIES = [
  'Time-Series',
  'SPC',
  'Statistical',
  'Categorical',
  'Flow / Hierarchy',
  'Industrial',
  'Heatmap',
  'Event',
  'Scheduling',
  'Tabular',
  '3D',
]

export function getChartDefinition(id: ChartTypeId): ChartDefinition {
  const def = CHART_DEFINITIONS.find((d) => d.id === id)
  if (!def) throw new Error(`Unknown chart type ${id}`)
  return def
}

export function getTierLabel(tier: ChartTier): string {
  switch (tier) {
    case 'initial': return 'Standard'
    case 'mid':     return 'Advanced'
    case 'late':    return 'Specialized'
  }
}
